name: ESP-IDF Build Check
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build ESP-IDF project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1 # Match your local version
          target: esp32
